#!/usr/bin/env php
<?php
/**
 * Date: 26.04.20
 * Time: 0:33
 */

declare(strict_types=1);

use KSSConsole\App;

require_once 'vendor/autoload.php';

$kss = new \KSS\KSSEngine('localhost', 3306, 'kss', 'root', '123');
$commands = new \KSSConsole\Commands($kss);

$app = new App($argv, $commands);
$app->run();
